// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopOnline.Data.EF;

namespace ShopOnline.Data.Migrations
{
    [DbContext(typeof(ShopOnlineDBContext))]
    [Migration("20210617120513_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ShopOnline.Data.Entities.CART", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CREATED_DATE")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IS_DELETED")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<double>("PRICE")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<Guid>("PRODUCT_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QUANTITY")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("ID");

                    b.HasIndex("PRODUCT_ID");

                    b.ToTable("CART");
                });

            modelBuilder.Entity("ShopOnline.Data.Entities.CATEGORY", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CREATED_DATE")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IS_DELETED")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IS_SHOW_ON_HOME")
                        .HasColumnType("bit");

                    b.Property<Guid?>("PARENT_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SORT_ORDER")
                        .HasColumnType("int");

                    b.Property<int>("STATUS")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PARENT_ID");

                    b.ToTable("CATEGORY");
                });

            modelBuilder.Entity("ShopOnline.Data.Entities.CATEGORY_TRANSLATION", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CATEGORY_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CREATED_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("DESCRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DETAILS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IS_DELETED")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("LANGUAGE_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SEO_ALIAS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SEO_DESCRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SEO_TITLE")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CATEGORY_ID");

                    b.HasIndex("LANGUAGE_ID");

                    b.ToTable("CATEGORY_TRANSLATION");
                });

            modelBuilder.Entity("ShopOnline.Data.Entities.CONTACT", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CREATED_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("EMAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IS_DELETED")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MESSAGE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PHONE_NUMBER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("STATUS")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("CONTACT");
                });

            modelBuilder.Entity("ShopOnline.Data.Entities.LANGUAGE", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CREATED_DATE")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IS_DEFAULT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IS_DELETED")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("LANGUAGE");
                });

            modelBuilder.Entity("ShopOnline.Data.Entities.ORDER", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CREATED_DATE")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IS_DELETED")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("ORDER_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("SHIP_ADDRESS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SHIP_EMAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SHIP_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SHIP_PHONE_NUMBER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("STATUS")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("ORDER");
                });

            modelBuilder.Entity("ShopOnline.Data.Entities.ORDER_DETAIL", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CREATED_DATE")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IS_DELETED")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("ORDER_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("PRICE")
                        .HasColumnType("float");

                    b.Property<Guid>("PRODUCT_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QUANTITY")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ORDER_ID");

                    b.HasIndex("PRODUCT_ID");

                    b.ToTable("ORDER_DETAIL");
                });

            modelBuilder.Entity("ShopOnline.Data.Entities.PRODUCT", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CREATED_DATE")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IS_DELETED")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<double>("ORIGINAL_PRICE")
                        .HasColumnType("float");

                    b.Property<double>("SELLING_PRICE")
                        .HasColumnType("float");

                    b.Property<int>("STATUS")
                        .HasColumnType("int");

                    b.Property<int>("STOCK_AMOUNT")
                        .HasColumnType("int");

                    b.Property<int>("VIEW_COUNT")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("PRODUCT");
                });

            modelBuilder.Entity("ShopOnline.Data.Entities.PRODUCT_IMAGE", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CAPTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CREATED_DATE")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IS_DEFAULT")
                        .HasColumnType("bit");

                    b.Property<bool>("IS_DELETED")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PATH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PRODUCT_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SORT_ORDER")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PRODUCT_ID");

                    b.ToTable("PRODUCT_IMAGE");
                });

            modelBuilder.Entity("ShopOnline.Data.Entities.PRODUCT_IN_CATEGORY", b =>
                {
                    b.Property<Guid>("CATEGORY_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PRODUCT_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CREATED_DATE")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IS_DELETED")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("CATEGORY_ID", "PRODUCT_ID");

                    b.HasIndex("PRODUCT_ID");

                    b.ToTable("PRODUCT_IN_CATEGORY");
                });

            modelBuilder.Entity("ShopOnline.Data.Entities.PRODUCT_TRANSLATION", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CREATED_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("DESCRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DETAILS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IS_DELETED")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("LANGUAGE_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PRODUCT_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SEO_ALIAS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SEO_DESCRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SEO_TITLE")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("LANGUAGE_ID");

                    b.HasIndex("PRODUCT_ID");

                    b.ToTable("PRODUCT_TRANSLATION");
                });

            modelBuilder.Entity("ShopOnline.Data.Entities.PROMOTION", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("APPLIED_PRODUCTIDS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CREATED_DATE")
                        .HasColumnType("datetime2");

                    b.Property<double>("DISCOUNT_AMOUNT")
                        .HasColumnType("float");

                    b.Property<double>("DISCOUNT_PERCENT")
                        .HasColumnType("float");

                    b.Property<DateTime>("FROM_DATE")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IS_APPLY_FOR_ALL")
                        .HasColumnType("bit");

                    b.Property<bool>("IS_DELETED")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("STATUS")
                        .HasColumnType("int");

                    b.Property<DateTime>("TO_DATE")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("PROMOTION");
                });

            modelBuilder.Entity("ShopOnline.Data.Entities.CART", b =>
                {
                    b.HasOne("ShopOnline.Data.Entities.PRODUCT", "PRODUCT")
                        .WithMany("CARTS")
                        .HasForeignKey("PRODUCT_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShopOnline.Data.Entities.CATEGORY", b =>
                {
                    b.HasOne("ShopOnline.Data.Entities.CATEGORY", "PARENT_CATEGORY")
                        .WithMany("CHILD_CATEGORIES")
                        .HasForeignKey("PARENT_ID");
                });

            modelBuilder.Entity("ShopOnline.Data.Entities.CATEGORY_TRANSLATION", b =>
                {
                    b.HasOne("ShopOnline.Data.Entities.CATEGORY", "CATEGORY")
                        .WithMany("CATEGORY_TRANSLATIONS")
                        .HasForeignKey("CATEGORY_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShopOnline.Data.Entities.LANGUAGE", "LANGUAGE")
                        .WithMany("CATEGORY_TRANSLATIONS")
                        .HasForeignKey("LANGUAGE_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShopOnline.Data.Entities.ORDER_DETAIL", b =>
                {
                    b.HasOne("ShopOnline.Data.Entities.ORDER", "ORDER")
                        .WithMany("ORDER_DETAILS")
                        .HasForeignKey("ORDER_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShopOnline.Data.Entities.PRODUCT", "PRODUCT")
                        .WithMany("ORDER_DETAILS")
                        .HasForeignKey("PRODUCT_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShopOnline.Data.Entities.PRODUCT_IMAGE", b =>
                {
                    b.HasOne("ShopOnline.Data.Entities.PRODUCT", "PRODUCT")
                        .WithMany("PRODUCT_IMAGES")
                        .HasForeignKey("PRODUCT_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShopOnline.Data.Entities.PRODUCT_IN_CATEGORY", b =>
                {
                    b.HasOne("ShopOnline.Data.Entities.CATEGORY", "CATEGORY")
                        .WithMany("PRODUCT_IN_CATEGORIES")
                        .HasForeignKey("CATEGORY_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShopOnline.Data.Entities.PRODUCT", "PRODUCT")
                        .WithMany("PRODUCT_IN_CATEGORIES")
                        .HasForeignKey("PRODUCT_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShopOnline.Data.Entities.PRODUCT_TRANSLATION", b =>
                {
                    b.HasOne("ShopOnline.Data.Entities.LANGUAGE", "LANGUAGE")
                        .WithMany("PRODUCT_TRANSLATIONS")
                        .HasForeignKey("LANGUAGE_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShopOnline.Data.Entities.PRODUCT", "PRODUCT")
                        .WithMany("PRODUCT_TRANSLATIONS")
                        .HasForeignKey("PRODUCT_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
